# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project'
require_relative '../lib/mj_remote_notification_center'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'dummy'

  app.frameworks    += [ "GameKit" ]

  app.codesign_certificate = "Mark Josef"
  app.identifier = "*"
  app.provisioning_profile = "Provisioning_Profile.mobileprovision"

end
